export const message={
    USERNOTLOGGEDIN:"USER NOT LOGGED IN",
    USERNOTSIGNEDUP:'USER NOT SIGNED UP',
    UNAUTHORIZEDACCESS:'UNAUTHORIZED ACCESS',
    INVALIDCREDENTIALS:'INVALID CREDENTIALS',
    USERSIGNEDUP:'USER SUCESSFULLY SIGNEDUP',
    USERLOGGEDIN:'USER LOGGED IN SUCCESSFULLY',
    USERLOGEDDOUT:'USER LOGGED OUT SUCCESSFULLY',
    USERUPDATED:'USER UPDATED SUCCESSFULLY',
    USERDELETED:'USER DELETED SUCCESFULLY',
    TOKENNOTVERIFIED:'TOKEN NOT VERIFIED',
    INTERNALSERVERORR:'INTERNAL SERVER ERROR',
    USERNOTFOUND:'USER NOT FOUND',


    CAREGORYCREATED:"CATEGORY SUCCESSFULLY CREATED",
    CATEGORYUPDATED:"CATEGORY SUCESSFULLY UPDATED",
    CATEGORYDELETED:"CATEGORY SUCESSFULLY DELETED",
    CATEGORYNOTFOUND:"CATEGORY NOT FOUND",

    PRODUCTCREATED:"PRODUCT SUCESSFULLY CREATED",
    PRODUCTUPDATED:"PRODUCT SUCESSFULLYUPDATED",
    PRODUCTDELETED:"PRODUCT SUCESSFULLY DELETED",
    PRODUCTNOTFOUND:"PRODUCT NOT FOUND"
}